// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: train/v1/train.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 训练周期信息请求
type TrainingEpochInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 任务ID
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// 当前周期
	Epoch int32 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// 预估剩余时间(秒)
	EstimatedTimeLeft int64 `protobuf:"varint,3,opt,name=estimated_time_left,json=estimatedTimeLeft,proto3" json:"estimated_time_left,omitempty"`
	// 动态指标字段
	DynamicFields map[string]string `protobuf:"bytes,4,rep,name=dynamic_fields,json=dynamicFields,proto3" json:"dynamic_fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainingEpochInfoRequest) Reset() {
	*x = TrainingEpochInfoRequest{}
	mi := &file_train_v1_train_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingEpochInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingEpochInfoRequest) ProtoMessage() {}

func (x *TrainingEpochInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_train_v1_train_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingEpochInfoRequest.ProtoReflect.Descriptor instead.
func (*TrainingEpochInfoRequest) Descriptor() ([]byte, []int) {
	return file_train_v1_train_proto_rawDescGZIP(), []int{0}
}

func (x *TrainingEpochInfoRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TrainingEpochInfoRequest) GetEpoch() int32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *TrainingEpochInfoRequest) GetEstimatedTimeLeft() int64 {
	if x != nil {
		return x.EstimatedTimeLeft
	}
	return 0
}

func (x *TrainingEpochInfoRequest) GetDynamicFields() map[string]string {
	if x != nil {
		return x.DynamicFields
	}
	return nil
}

// 训练检查点请求
type TrainingCheckpointRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 任务ID
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// 当前周期
	Epoch int32 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// 检查点路径
	CheckpointPath string `protobuf:"bytes,3,opt,name=checkpoint_path,json=checkpointPath,proto3" json:"checkpoint_path,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TrainingCheckpointRequest) Reset() {
	*x = TrainingCheckpointRequest{}
	mi := &file_train_v1_train_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingCheckpointRequest) ProtoMessage() {}

func (x *TrainingCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_train_v1_train_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingCheckpointRequest.ProtoReflect.Descriptor instead.
func (*TrainingCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_train_v1_train_proto_rawDescGZIP(), []int{1}
}

func (x *TrainingCheckpointRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TrainingCheckpointRequest) GetEpoch() int32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *TrainingCheckpointRequest) GetCheckpointPath() string {
	if x != nil {
		return x.CheckpointPath
	}
	return ""
}

// 训练任务结果请求
type TrainingTaskResultRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 任务ID
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// 最优周期
	BestEpoch int32 `protobuf:"varint,2,opt,name=best_epoch,json=bestEpoch,proto3" json:"best_epoch,omitempty"`
	// 最优模型路径
	BestModelPath string `protobuf:"bytes,3,opt,name=best_model_path,json=bestModelPath,proto3" json:"best_model_path,omitempty"`
	// 最终模型路径
	FinalModelPath string `protobuf:"bytes,4,opt,name=final_model_path,json=finalModelPath,proto3" json:"final_model_path,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TrainingTaskResultRequest) Reset() {
	*x = TrainingTaskResultRequest{}
	mi := &file_train_v1_train_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingTaskResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingTaskResultRequest) ProtoMessage() {}

func (x *TrainingTaskResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_train_v1_train_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingTaskResultRequest.ProtoReflect.Descriptor instead.
func (*TrainingTaskResultRequest) Descriptor() ([]byte, []int) {
	return file_train_v1_train_proto_rawDescGZIP(), []int{2}
}

func (x *TrainingTaskResultRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TrainingTaskResultRequest) GetBestEpoch() int32 {
	if x != nil {
		return x.BestEpoch
	}
	return 0
}

func (x *TrainingTaskResultRequest) GetBestModelPath() string {
	if x != nil {
		return x.BestModelPath
	}
	return ""
}

func (x *TrainingTaskResultRequest) GetFinalModelPath() string {
	if x != nil {
		return x.FinalModelPath
	}
	return ""
}

// 通用训练响应
type TrainingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// 响应消息
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainingResponse) Reset() {
	*x = TrainingResponse{}
	mi := &file_train_v1_train_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingResponse) ProtoMessage() {}

func (x *TrainingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_train_v1_train_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingResponse.ProtoReflect.Descriptor instead.
func (*TrainingResponse) Descriptor() ([]byte, []int) {
	return file_train_v1_train_proto_rawDescGZIP(), []int{3}
}

func (x *TrainingResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TrainingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_train_v1_train_proto protoreflect.FileDescriptor

const file_train_v1_train_proto_rawDesc = "" +
	"\n" +
	"\x14train/v1/train.proto\x12\fapi.train.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"\xa6\x02\n" +
	"\x18TrainingEpochInfoRequest\x12 \n" +
	"\atask_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06taskId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x05R\x05epoch\x12.\n" +
	"\x13estimated_time_left\x18\x03 \x01(\x03R\x11estimatedTimeLeft\x12`\n" +
	"\x0edynamic_fields\x18\x04 \x03(\v29.api.train.v1.TrainingEpochInfoRequest.DynamicFieldsEntryR\rdynamicFields\x1a@\n" +
	"\x12DynamicFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"|\n" +
	"\x19TrainingCheckpointRequest\x12 \n" +
	"\atask_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06taskId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x05R\x05epoch\x12'\n" +
	"\x0fcheckpoint_path\x18\x03 \x01(\tR\x0echeckpointPath\"\xae\x01\n" +
	"\x19TrainingTaskResultRequest\x12 \n" +
	"\atask_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06taskId\x12\x1d\n" +
	"\n" +
	"best_epoch\x18\x02 \x01(\x05R\tbestEpoch\x12&\n" +
	"\x0fbest_model_path\x18\x03 \x01(\tR\rbestModelPath\x12(\n" +
	"\x10final_model_path\x18\x04 \x01(\tR\x0efinalModelPath\"@\n" +
	"\x10TrainingResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xea\x02\n" +
	"\x10TrainInfoService\x12l\n" +
	"\tEpochInfo\x12&.api.train.v1.TrainingEpochInfoRequest\x1a\x1e.api.train.v1.TrainingResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/train/epoch\x12w\n" +
	"\x0eCheckpointInfo\x12'.api.train.v1.TrainingCheckpointRequest\x1a\x1e.api.train.v1.TrainingResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/train/checkpoint\x12o\n" +
	"\n" +
	"FinishInfo\x12'.api.train.v1.TrainingTaskResultRequest\x1a\x1e.api.train.v1.TrainingResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/train/finishB,\n" +
	"\fapi.train.v1P\x01Z\x1aalgo-agent/api/train/v1;v1b\x06proto3"

var (
	file_train_v1_train_proto_rawDescOnce sync.Once
	file_train_v1_train_proto_rawDescData []byte
)

func file_train_v1_train_proto_rawDescGZIP() []byte {
	file_train_v1_train_proto_rawDescOnce.Do(func() {
		file_train_v1_train_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_train_v1_train_proto_rawDesc), len(file_train_v1_train_proto_rawDesc)))
	})
	return file_train_v1_train_proto_rawDescData
}

var file_train_v1_train_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_train_v1_train_proto_goTypes = []any{
	(*TrainingEpochInfoRequest)(nil),  // 0: api.train.v1.TrainingEpochInfoRequest
	(*TrainingCheckpointRequest)(nil), // 1: api.train.v1.TrainingCheckpointRequest
	(*TrainingTaskResultRequest)(nil), // 2: api.train.v1.TrainingTaskResultRequest
	(*TrainingResponse)(nil),          // 3: api.train.v1.TrainingResponse
	nil,                               // 4: api.train.v1.TrainingEpochInfoRequest.DynamicFieldsEntry
}
var file_train_v1_train_proto_depIdxs = []int32{
	4, // 0: api.train.v1.TrainingEpochInfoRequest.dynamic_fields:type_name -> api.train.v1.TrainingEpochInfoRequest.DynamicFieldsEntry
	0, // 1: api.train.v1.TrainInfoService.EpochInfo:input_type -> api.train.v1.TrainingEpochInfoRequest
	1, // 2: api.train.v1.TrainInfoService.CheckpointInfo:input_type -> api.train.v1.TrainingCheckpointRequest
	2, // 3: api.train.v1.TrainInfoService.FinishInfo:input_type -> api.train.v1.TrainingTaskResultRequest
	3, // 4: api.train.v1.TrainInfoService.EpochInfo:output_type -> api.train.v1.TrainingResponse
	3, // 5: api.train.v1.TrainInfoService.CheckpointInfo:output_type -> api.train.v1.TrainingResponse
	3, // 6: api.train.v1.TrainInfoService.FinishInfo:output_type -> api.train.v1.TrainingResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_train_v1_train_proto_init() }
func file_train_v1_train_proto_init() {
	if File_train_v1_train_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_train_v1_train_proto_rawDesc), len(file_train_v1_train_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_train_v1_train_proto_goTypes,
		DependencyIndexes: file_train_v1_train_proto_depIdxs,
		MessageInfos:      file_train_v1_train_proto_msgTypes,
	}.Build()
	File_train_v1_train_proto = out.File
	file_train_v1_train_proto_goTypes = nil
	file_train_v1_train_proto_depIdxs = nil
}
