// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: rabbitmq/v1/rabbitmq.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RabbitMQService_SendMessage_FullMethodName   = "/api.rabbitmq.v1.RabbitMQService/SendMessage"
	RabbitMQService_SendToQueue_FullMethodName   = "/api.rabbitmq.v1.RabbitMQService/SendToQueue"
	RabbitMQService_SendToService_FullMethodName = "/api.rabbitmq.v1.RabbitMQService/SendToService"
)

// RabbitMQServiceClient is the client API for RabbitMQService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RabbitMQ服务接口定义
type RabbitMQServiceClient interface {
	// 发送消息到特定交换机和路由键
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageReply, error)
	// 发送消息到特定队列
	SendToQueue(ctx context.Context, in *SendToQueueRequest, opts ...grpc.CallOption) (*SendToQueueReply, error)
	// 发送消息到特定服务
	SendToService(ctx context.Context, in *SendToServiceRequest, opts ...grpc.CallOption) (*SendToServiceReply, error)
}

type rabbitMQServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRabbitMQServiceClient(cc grpc.ClientConnInterface) RabbitMQServiceClient {
	return &rabbitMQServiceClient{cc}
}

func (c *rabbitMQServiceClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageReply)
	err := c.cc.Invoke(ctx, RabbitMQService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rabbitMQServiceClient) SendToQueue(ctx context.Context, in *SendToQueueRequest, opts ...grpc.CallOption) (*SendToQueueReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendToQueueReply)
	err := c.cc.Invoke(ctx, RabbitMQService_SendToQueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rabbitMQServiceClient) SendToService(ctx context.Context, in *SendToServiceRequest, opts ...grpc.CallOption) (*SendToServiceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendToServiceReply)
	err := c.cc.Invoke(ctx, RabbitMQService_SendToService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RabbitMQServiceServer is the server API for RabbitMQService service.
// All implementations must embed UnimplementedRabbitMQServiceServer
// for forward compatibility.
//
// RabbitMQ服务接口定义
type RabbitMQServiceServer interface {
	// 发送消息到特定交换机和路由键
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageReply, error)
	// 发送消息到特定队列
	SendToQueue(context.Context, *SendToQueueRequest) (*SendToQueueReply, error)
	// 发送消息到特定服务
	SendToService(context.Context, *SendToServiceRequest) (*SendToServiceReply, error)
	mustEmbedUnimplementedRabbitMQServiceServer()
}

// UnimplementedRabbitMQServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRabbitMQServiceServer struct{}

func (UnimplementedRabbitMQServiceServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedRabbitMQServiceServer) SendToQueue(context.Context, *SendToQueueRequest) (*SendToQueueReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendToQueue not implemented")
}
func (UnimplementedRabbitMQServiceServer) SendToService(context.Context, *SendToServiceRequest) (*SendToServiceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendToService not implemented")
}
func (UnimplementedRabbitMQServiceServer) mustEmbedUnimplementedRabbitMQServiceServer() {}
func (UnimplementedRabbitMQServiceServer) testEmbeddedByValue()                         {}

// UnsafeRabbitMQServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RabbitMQServiceServer will
// result in compilation errors.
type UnsafeRabbitMQServiceServer interface {
	mustEmbedUnimplementedRabbitMQServiceServer()
}

func RegisterRabbitMQServiceServer(s grpc.ServiceRegistrar, srv RabbitMQServiceServer) {
	// If the following call pancis, it indicates UnimplementedRabbitMQServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RabbitMQService_ServiceDesc, srv)
}

func _RabbitMQService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RabbitMQServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RabbitMQService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RabbitMQServiceServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RabbitMQService_SendToQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendToQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RabbitMQServiceServer).SendToQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RabbitMQService_SendToQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RabbitMQServiceServer).SendToQueue(ctx, req.(*SendToQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RabbitMQService_SendToService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendToServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RabbitMQServiceServer).SendToService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RabbitMQService_SendToService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RabbitMQServiceServer).SendToService(ctx, req.(*SendToServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RabbitMQService_ServiceDesc is the grpc.ServiceDesc for RabbitMQService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RabbitMQService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.rabbitmq.v1.RabbitMQService",
	HandlerType: (*RabbitMQServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _RabbitMQService_SendMessage_Handler,
		},
		{
			MethodName: "SendToQueue",
			Handler:    _RabbitMQService_SendToQueue_Handler,
		},
		{
			MethodName: "SendToService",
			Handler:    _RabbitMQService_SendToService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rabbitmq/v1/rabbitmq.proto",
}
