// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v5.29.3
// source: rabbitmq/v1/rabbitmq.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationRabbitMQSendMessage = "/rabbitmq.v1.RabbitMQ/SendMessage"
const OperationRabbitMQSendToService = "/rabbitmq.v1.RabbitMQ/SendToService"

type RabbitMQHTTPServer interface {
	// SendMessage 发送消息
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageReply, error)
	// SendToService 发送消息到特定服务
	SendToService(context.Context, *SendToServiceRequest) (*SendToServiceReply, error)
}

func RegisterRabbitMQHTTPServer(s *http.Server, srv RabbitMQHTTPServer) {
	r := s.Route("/")
	r.POST("/rabbitmq/message", _RabbitMQ_SendMessage0_HTTP_Handler(srv))
	r.POST("/rabbitmq/service", _RabbitMQ_SendToService0_HTTP_Handler(srv))
}

func _RabbitMQ_SendMessage0_HTTP_Handler(srv RabbitMQHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SendMessageRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRabbitMQSendMessage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SendMessage(ctx, req.(*SendMessageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SendMessageReply)
		return ctx.Result(200, reply)
	}
}

func _RabbitMQ_SendToService0_HTTP_Handler(srv RabbitMQHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SendToServiceRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRabbitMQSendToService)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SendToService(ctx, req.(*SendToServiceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SendToServiceReply)
		return ctx.Result(200, reply)
	}
}

type RabbitMQHTTPClient interface {
	SendMessage(ctx context.Context, req *SendMessageRequest, opts ...http.CallOption) (rsp *SendMessageReply, err error)
	SendToService(ctx context.Context, req *SendToServiceRequest, opts ...http.CallOption) (rsp *SendToServiceReply, err error)
}

type RabbitMQHTTPClientImpl struct {
	cc *http.Client
}

func NewRabbitMQHTTPClient(client *http.Client) RabbitMQHTTPClient {
	return &RabbitMQHTTPClientImpl{client}
}

func (c *RabbitMQHTTPClientImpl) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...http.CallOption) (*SendMessageReply, error) {
	var out SendMessageReply
	pattern := "/rabbitmq/message"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRabbitMQSendMessage))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *RabbitMQHTTPClientImpl) SendToService(ctx context.Context, in *SendToServiceRequest, opts ...http.CallOption) (*SendToServiceReply, error) {
	var out SendToServiceReply
	pattern := "/rabbitmq/service"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRabbitMQSendToService))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
