// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: rabbitmq/v1/rabbitmq.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RabbitMQ_SendMessage_FullMethodName   = "/rabbitmq.v1.RabbitMQ/SendMessage"
	RabbitMQ_SendToService_FullMethodName = "/rabbitmq.v1.RabbitMQ/SendToService"
)

// RabbitMQClient is the client API for RabbitMQ service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RabbitMQ服务定义
type RabbitMQClient interface {
	// 发送消息
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageReply, error)
	// 发送消息到特定服务
	SendToService(ctx context.Context, in *SendToServiceRequest, opts ...grpc.CallOption) (*SendToServiceReply, error)
}

type rabbitMQClient struct {
	cc grpc.ClientConnInterface
}

func NewRabbitMQClient(cc grpc.ClientConnInterface) RabbitMQClient {
	return &rabbitMQClient{cc}
}

func (c *rabbitMQClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageReply)
	err := c.cc.Invoke(ctx, RabbitMQ_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rabbitMQClient) SendToService(ctx context.Context, in *SendToServiceRequest, opts ...grpc.CallOption) (*SendToServiceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendToServiceReply)
	err := c.cc.Invoke(ctx, RabbitMQ_SendToService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RabbitMQServer is the server API for RabbitMQ service.
// All implementations must embed UnimplementedRabbitMQServer
// for forward compatibility.
//
// RabbitMQ服务定义
type RabbitMQServer interface {
	// 发送消息
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageReply, error)
	// 发送消息到特定服务
	SendToService(context.Context, *SendToServiceRequest) (*SendToServiceReply, error)
	mustEmbedUnimplementedRabbitMQServer()
}

// UnimplementedRabbitMQServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRabbitMQServer struct{}

func (UnimplementedRabbitMQServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedRabbitMQServer) SendToService(context.Context, *SendToServiceRequest) (*SendToServiceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendToService not implemented")
}
func (UnimplementedRabbitMQServer) mustEmbedUnimplementedRabbitMQServer() {}
func (UnimplementedRabbitMQServer) testEmbeddedByValue()                  {}

// UnsafeRabbitMQServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RabbitMQServer will
// result in compilation errors.
type UnsafeRabbitMQServer interface {
	mustEmbedUnimplementedRabbitMQServer()
}

func RegisterRabbitMQServer(s grpc.ServiceRegistrar, srv RabbitMQServer) {
	// If the following call pancis, it indicates UnimplementedRabbitMQServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RabbitMQ_ServiceDesc, srv)
}

func _RabbitMQ_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RabbitMQServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RabbitMQ_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RabbitMQServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RabbitMQ_SendToService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendToServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RabbitMQServer).SendToService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RabbitMQ_SendToService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RabbitMQServer).SendToService(ctx, req.(*SendToServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RabbitMQ_ServiceDesc is the grpc.ServiceDesc for RabbitMQ service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RabbitMQ_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rabbitmq.v1.RabbitMQ",
	HandlerType: (*RabbitMQServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _RabbitMQ_SendMessage_Handler,
		},
		{
			MethodName: "SendToService",
			Handler:    _RabbitMQ_SendToService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rabbitmq/v1/rabbitmq.proto",
}
