// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: extract/v1/extract.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExtractInfoService_ResultInfo_FullMethodName = "/api.extract.v1.ExtractInfoService/ResultInfo"
)

// ExtractInfoServiceClient is the client API for ExtractInfoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 提取任务服务接口定义
type ExtractInfoServiceClient interface {
	// 处理提取任务结果
	ResultInfo(ctx context.Context, in *ExtractTaskResultRequest, opts ...grpc.CallOption) (*ExtractResponse, error)
}

type extractInfoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExtractInfoServiceClient(cc grpc.ClientConnInterface) ExtractInfoServiceClient {
	return &extractInfoServiceClient{cc}
}

func (c *extractInfoServiceClient) ResultInfo(ctx context.Context, in *ExtractTaskResultRequest, opts ...grpc.CallOption) (*ExtractResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtractResponse)
	err := c.cc.Invoke(ctx, ExtractInfoService_ResultInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExtractInfoServiceServer is the server API for ExtractInfoService service.
// All implementations must embed UnimplementedExtractInfoServiceServer
// for forward compatibility.
//
// 提取任务服务接口定义
type ExtractInfoServiceServer interface {
	// 处理提取任务结果
	ResultInfo(context.Context, *ExtractTaskResultRequest) (*ExtractResponse, error)
	mustEmbedUnimplementedExtractInfoServiceServer()
}

// UnimplementedExtractInfoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExtractInfoServiceServer struct{}

func (UnimplementedExtractInfoServiceServer) ResultInfo(context.Context, *ExtractTaskResultRequest) (*ExtractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResultInfo not implemented")
}
func (UnimplementedExtractInfoServiceServer) mustEmbedUnimplementedExtractInfoServiceServer() {}
func (UnimplementedExtractInfoServiceServer) testEmbeddedByValue()                            {}

// UnsafeExtractInfoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExtractInfoServiceServer will
// result in compilation errors.
type UnsafeExtractInfoServiceServer interface {
	mustEmbedUnimplementedExtractInfoServiceServer()
}

func RegisterExtractInfoServiceServer(s grpc.ServiceRegistrar, srv ExtractInfoServiceServer) {
	// If the following call pancis, it indicates UnimplementedExtractInfoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExtractInfoService_ServiceDesc, srv)
}

func _ExtractInfoService_ResultInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtractTaskResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtractInfoServiceServer).ResultInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtractInfoService_ResultInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtractInfoServiceServer).ResultInfo(ctx, req.(*ExtractTaskResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExtractInfoService_ServiceDesc is the grpc.ServiceDesc for ExtractInfoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExtractInfoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.extract.v1.ExtractInfoService",
	HandlerType: (*ExtractInfoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResultInfo",
			Handler:    _ExtractInfoService_ResultInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "extract/v1/extract.proto",
}
