// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: extract/v1/extract.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 提取任务结果请求
type ExtractTaskResultRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 任务ID
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// 模型路径
	ModelPath     string `protobuf:"bytes,2,opt,name=model_path,json=modelPath,proto3" json:"model_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractTaskResultRequest) Reset() {
	*x = ExtractTaskResultRequest{}
	mi := &file_extract_v1_extract_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractTaskResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractTaskResultRequest) ProtoMessage() {}

func (x *ExtractTaskResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extract_v1_extract_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractTaskResultRequest.ProtoReflect.Descriptor instead.
func (*ExtractTaskResultRequest) Descriptor() ([]byte, []int) {
	return file_extract_v1_extract_proto_rawDescGZIP(), []int{0}
}

func (x *ExtractTaskResultRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ExtractTaskResultRequest) GetModelPath() string {
	if x != nil {
		return x.ModelPath
	}
	return ""
}

// 通用提取响应
type ExtractResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// 响应消息
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractResponse) Reset() {
	*x = ExtractResponse{}
	mi := &file_extract_v1_extract_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractResponse) ProtoMessage() {}

func (x *ExtractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_extract_v1_extract_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractResponse.ProtoReflect.Descriptor instead.
func (*ExtractResponse) Descriptor() ([]byte, []int) {
	return file_extract_v1_extract_proto_rawDescGZIP(), []int{1}
}

func (x *ExtractResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ExtractResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_extract_v1_extract_proto protoreflect.FileDescriptor

const file_extract_v1_extract_proto_rawDesc = "" +
	"\n" +
	"\x18extract/v1/extract.proto\x12\x0eapi.extract.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"d\n" +
	"\x18ExtractTaskResultRequest\x12 \n" +
	"\atask_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06taskId\x12&\n" +
	"\n" +
	"model_path\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tmodelPath\"?\n" +
	"\x0fExtractResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x89\x01\n" +
	"\x12ExtractInfoService\x12s\n" +
	"\n" +
	"ResultInfo\x12(.api.extract.v1.ExtractTaskResultRequest\x1a\x1f.api.extract.v1.ExtractResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/extract/finishB0\n" +
	"\x0eapi.extract.v1P\x01Z\x1calgo-agent/api/extract/v1;v1b\x06proto3"

var (
	file_extract_v1_extract_proto_rawDescOnce sync.Once
	file_extract_v1_extract_proto_rawDescData []byte
)

func file_extract_v1_extract_proto_rawDescGZIP() []byte {
	file_extract_v1_extract_proto_rawDescOnce.Do(func() {
		file_extract_v1_extract_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_extract_v1_extract_proto_rawDesc), len(file_extract_v1_extract_proto_rawDesc)))
	})
	return file_extract_v1_extract_proto_rawDescData
}

var file_extract_v1_extract_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_extract_v1_extract_proto_goTypes = []any{
	(*ExtractTaskResultRequest)(nil), // 0: api.extract.v1.ExtractTaskResultRequest
	(*ExtractResponse)(nil),          // 1: api.extract.v1.ExtractResponse
}
var file_extract_v1_extract_proto_depIdxs = []int32{
	0, // 0: api.extract.v1.ExtractInfoService.ResultInfo:input_type -> api.extract.v1.ExtractTaskResultRequest
	1, // 1: api.extract.v1.ExtractInfoService.ResultInfo:output_type -> api.extract.v1.ExtractResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_extract_v1_extract_proto_init() }
func file_extract_v1_extract_proto_init() {
	if File_extract_v1_extract_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_extract_v1_extract_proto_rawDesc), len(file_extract_v1_extract_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_extract_v1_extract_proto_goTypes,
		DependencyIndexes: file_extract_v1_extract_proto_depIdxs,
		MessageInfos:      file_extract_v1_extract_proto_msgTypes,
	}.Build()
	File_extract_v1_extract_proto = out.File
	file_extract_v1_extract_proto_goTypes = nil
	file_extract_v1_extract_proto_depIdxs = nil
}
