server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test?parseTime=True&loc=Local
  redis:
    addr: 192.168.110.238:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  rabbitmq:
    host: 192.168.110.101
    port: 5672
    username: admin
    password: admin
    vhost: /
    group: dev
    default_exchange_name: zh_node_exchange
    default_routing_key: zh_node_routing
    service_queue_prefix: _zh_service_
    node_queue_prefix: _zh_node_
    node_name: dev-go-design
    listener:
      retry_max_attempts: 3
      retry_initial_interval: 1s
      retry_multiplier: 2
      retry_max_interval: 10s
  docker:
    host: unix:///var/run/docker.sock
  oss:
    endpoint: 192.168.110.101:9400
    access_key: 4dd7X0NpMTHZpjkJ8ucl
    secret_key: sHF4NdInnRgNY17hKMX1ditXkKnJaiUJeykhKHrj
  node:
    node_name: dev-go-design
    node_host: 192.168.110.238
    docker_host: host.docker.internal
  mapping_file_path: /data/node_data
  services:
    # 训练服务
    train: zhihua-intellitrain
    # 部署服务
    deploy: zhihua-intellideploy
