// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: deploy/v1/deploy.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 部署请求消息
type DeployRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 推理服务ID
	ServiceId string `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	// 推理服务操作
	Op int32 `protobuf:"varint,2,opt,name=op,proto3" json:"op,omitempty"`
	// 算法脚本所在minio存储桶
	AlgorithmScriptBucket string `protobuf:"bytes,3,opt,name=algorithm_script_bucket,json=algorithmScriptBucket,proto3" json:"algorithm_script_bucket,omitempty"`
	// 算法脚本所在minio的存储地址
	AlgorithmScriptPath string `protobuf:"bytes,4,opt,name=algorithm_script_path,json=algorithmScriptPath,proto3" json:"algorithm_script_path,omitempty"`
	// 推理权重模型所在bucket
	ModelBucket string `protobuf:"bytes,5,opt,name=model_bucket,json=modelBucket,proto3" json:"model_bucket,omitempty"`
	// 推理权重模型所在url地址
	ModelPath string `protobuf:"bytes,6,opt,name=model_path,json=modelPath,proto3" json:"model_path,omitempty"`
	// 算法推理用docker image名称
	InferImageName string `protobuf:"bytes,7,opt,name=infer_image_name,json=inferImageName,proto3" json:"infer_image_name,omitempty"`
	// 推理用镜像bucket名称
	InferImageBucket string `protobuf:"bytes,8,opt,name=infer_image_bucket,json=inferImageBucket,proto3" json:"infer_image_bucket,omitempty"`
	// 推理用docker image在minio的存储地址
	InferImagePath string `protobuf:"bytes,9,opt,name=infer_image_path,json=inferImagePath,proto3" json:"infer_image_path,omitempty"`
	// 标注标签
	DatasetLabel string `protobuf:"bytes,10,opt,name=dataset_label,json=datasetLabel,proto3" json:"dataset_label,omitempty"`
	// 推理服务端口
	ServicePort int32 `protobuf:"varint,11,opt,name=service_port,json=servicePort,proto3" json:"service_port,omitempty"`
	// 推理服务启动参数
	Args          []string `protobuf:"bytes,12,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployRequest) Reset() {
	*x = DeployRequest{}
	mi := &file_deploy_v1_deploy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployRequest) ProtoMessage() {}

func (x *DeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deploy_v1_deploy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployRequest.ProtoReflect.Descriptor instead.
func (*DeployRequest) Descriptor() ([]byte, []int) {
	return file_deploy_v1_deploy_proto_rawDescGZIP(), []int{0}
}

func (x *DeployRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *DeployRequest) GetOp() int32 {
	if x != nil {
		return x.Op
	}
	return 0
}

func (x *DeployRequest) GetAlgorithmScriptBucket() string {
	if x != nil {
		return x.AlgorithmScriptBucket
	}
	return ""
}

func (x *DeployRequest) GetAlgorithmScriptPath() string {
	if x != nil {
		return x.AlgorithmScriptPath
	}
	return ""
}

func (x *DeployRequest) GetModelBucket() string {
	if x != nil {
		return x.ModelBucket
	}
	return ""
}

func (x *DeployRequest) GetModelPath() string {
	if x != nil {
		return x.ModelPath
	}
	return ""
}

func (x *DeployRequest) GetInferImageName() string {
	if x != nil {
		return x.InferImageName
	}
	return ""
}

func (x *DeployRequest) GetInferImageBucket() string {
	if x != nil {
		return x.InferImageBucket
	}
	return ""
}

func (x *DeployRequest) GetInferImagePath() string {
	if x != nil {
		return x.InferImagePath
	}
	return ""
}

func (x *DeployRequest) GetDatasetLabel() string {
	if x != nil {
		return x.DatasetLabel
	}
	return ""
}

func (x *DeployRequest) GetServicePort() int32 {
	if x != nil {
		return x.ServicePort
	}
	return 0
}

func (x *DeployRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

// 部署响应消息
type DeployReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 推理服务 ID
	ServiceId string `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	// 推理服务状态
	ServiceStatus int32 `protobuf:"varint,2,opt,name=service_status,json=serviceStatus,proto3" json:"service_status,omitempty"`
	// 备注
	Remark        string `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployReply) Reset() {
	*x = DeployReply{}
	mi := &file_deploy_v1_deploy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployReply) ProtoMessage() {}

func (x *DeployReply) ProtoReflect() protoreflect.Message {
	mi := &file_deploy_v1_deploy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployReply.ProtoReflect.Descriptor instead.
func (*DeployReply) Descriptor() ([]byte, []int) {
	return file_deploy_v1_deploy_proto_rawDescGZIP(), []int{1}
}

func (x *DeployReply) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *DeployReply) GetServiceStatus() int32 {
	if x != nil {
		return x.ServiceStatus
	}
	return 0
}

func (x *DeployReply) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

// 销毁请求消息
type DestroyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyRequest) Reset() {
	*x = DestroyRequest{}
	mi := &file_deploy_v1_deploy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyRequest) ProtoMessage() {}

func (x *DestroyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deploy_v1_deploy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyRequest.ProtoReflect.Descriptor instead.
func (*DestroyRequest) Descriptor() ([]byte, []int) {
	return file_deploy_v1_deploy_proto_rawDescGZIP(), []int{2}
}

func (x *DestroyRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

// 销毁响应消息
type DestroyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyReply) Reset() {
	*x = DestroyReply{}
	mi := &file_deploy_v1_deploy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyReply) ProtoMessage() {}

func (x *DestroyReply) ProtoReflect() protoreflect.Message {
	mi := &file_deploy_v1_deploy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyReply.ProtoReflect.Descriptor instead.
func (*DestroyReply) Descriptor() ([]byte, []int) {
	return file_deploy_v1_deploy_proto_rawDescGZIP(), []int{3}
}

func (x *DestroyReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_deploy_v1_deploy_proto protoreflect.FileDescriptor

const file_deploy_v1_deploy_proto_rawDesc = "" +
	"\n" +
	"\x16deploy/v1/deploy.proto\x12\rapi.deploy.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"\xd3\x03\n" +
	"\rDeployRequest\x12&\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tserviceId\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\x05R\x02op\x126\n" +
	"\x17algorithm_script_bucket\x18\x03 \x01(\tR\x15algorithmScriptBucket\x122\n" +
	"\x15algorithm_script_path\x18\x04 \x01(\tR\x13algorithmScriptPath\x12!\n" +
	"\fmodel_bucket\x18\x05 \x01(\tR\vmodelBucket\x12\x1d\n" +
	"\n" +
	"model_path\x18\x06 \x01(\tR\tmodelPath\x12(\n" +
	"\x10infer_image_name\x18\a \x01(\tR\x0einferImageName\x12,\n" +
	"\x12infer_image_bucket\x18\b \x01(\tR\x10inferImageBucket\x12(\n" +
	"\x10infer_image_path\x18\t \x01(\tR\x0einferImagePath\x12#\n" +
	"\rdataset_label\x18\n" +
	" \x01(\tR\fdatasetLabel\x12!\n" +
	"\fservice_port\x18\v \x01(\x05R\vservicePort\x12\x12\n" +
	"\x04args\x18\f \x03(\tR\x04args\"k\n" +
	"\vDeployReply\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12%\n" +
	"\x0eservice_status\x18\x02 \x01(\x05R\rserviceStatus\x12\x16\n" +
	"\x06remark\x18\x03 \x01(\tR\x06remark\"8\n" +
	"\x0eDestroyRequest\x12&\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tserviceId\"(\n" +
	"\fDestroyReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xcd\x01\n" +
	"\rDeployService\x12Y\n" +
	"\x06Deploy\x12\x1c.api.deploy.v1.DeployRequest\x1a\x1a.api.deploy.v1.DeployReply\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/deploy/v1\x12a\n" +
	"\aDestroy\x12\x1d.api.deploy.v1.DestroyRequest\x1a\x1b.api.deploy.v1.DestroyReply\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/deploy/v1/destroyB.\n" +
	"\rapi.deploy.v1P\x01Z\x1balgo-agent/api/deploy/v1;v1b\x06proto3"

var (
	file_deploy_v1_deploy_proto_rawDescOnce sync.Once
	file_deploy_v1_deploy_proto_rawDescData []byte
)

func file_deploy_v1_deploy_proto_rawDescGZIP() []byte {
	file_deploy_v1_deploy_proto_rawDescOnce.Do(func() {
		file_deploy_v1_deploy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_deploy_v1_deploy_proto_rawDesc), len(file_deploy_v1_deploy_proto_rawDesc)))
	})
	return file_deploy_v1_deploy_proto_rawDescData
}

var file_deploy_v1_deploy_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_deploy_v1_deploy_proto_goTypes = []any{
	(*DeployRequest)(nil),  // 0: api.deploy.v1.DeployRequest
	(*DeployReply)(nil),    // 1: api.deploy.v1.DeployReply
	(*DestroyRequest)(nil), // 2: api.deploy.v1.DestroyRequest
	(*DestroyReply)(nil),   // 3: api.deploy.v1.DestroyReply
}
var file_deploy_v1_deploy_proto_depIdxs = []int32{
	0, // 0: api.deploy.v1.DeployService.Deploy:input_type -> api.deploy.v1.DeployRequest
	2, // 1: api.deploy.v1.DeployService.Destroy:input_type -> api.deploy.v1.DestroyRequest
	1, // 2: api.deploy.v1.DeployService.Deploy:output_type -> api.deploy.v1.DeployReply
	3, // 3: api.deploy.v1.DeployService.Destroy:output_type -> api.deploy.v1.DestroyReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_deploy_v1_deploy_proto_init() }
func file_deploy_v1_deploy_proto_init() {
	if File_deploy_v1_deploy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_deploy_v1_deploy_proto_rawDesc), len(file_deploy_v1_deploy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_deploy_v1_deploy_proto_goTypes,
		DependencyIndexes: file_deploy_v1_deploy_proto_depIdxs,
		MessageInfos:      file_deploy_v1_deploy_proto_msgTypes,
	}.Build()
	File_deploy_v1_deploy_proto = out.File
	file_deploy_v1_deploy_proto_goTypes = nil
	file_deploy_v1_deploy_proto_depIdxs = nil
}
